#!/bin/bash

if [ $# -ne 1 ]
then
  echo "Usage: `basename $0` {project_name}"
  exit $E_BADARGS
fi

if [ "${PWD##*/}" != "$1" ] 
then
  echo "Error: Current working directory is not $1"
  exit $E_BADARGS
fi

# Create run script and make it executable
echo "#!/bin/bash

clear ; ./setenv.sh go install $1 ; if [ \$? -eq 0 ]; then ./bin/$1; fi" > ./run
chmod +x ./run

# Create setenv.sh script and make it executable
echo "#!/bin/bash

export GOPATH=`pwd`
mkdir bin >& /dev/null
mkdir pkg >& /dev/null

eval \$@" > ./setenv.sh
chmod +x ./setenv.sh


# Make src directory and project directory
#mkdir src
mkdir -p src/$1

# Create hello world folder
echo "package main

import (
  \"log\"
)

func main() {
  log.Printf(\"Hello world\n\");
}" > ./src/$1/$1.go

#Create .gitignore file
echo "bin
pkg" > ./.gitignore
